name: chill_sounds
description: Relaxing sound app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  lottie: ^1.0.1

  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7

  provider: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  fluttertoast: ^8.0.6
  audioplayers: ^0.18.3
  connectivity_plus: ^1.0.1
  dio: ^5.0.3
  path_provider: ^2.0.1
  video_player: ^2.1.1
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.9.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logoicon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/background/
    - assets/icons/
    - assets/videos/
    - assets/icons/loader.json
    - assets/videos/vsplash3.mkv


  fonts:
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/PoppinsLight.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
    - family: PoppinsSB
      fonts:
        - asset: assets/fonts/PoppinsSB.ttf
    - family: PoppinsXlight
      fonts:
        - asset: assets/fonts/PoppinsXlight.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
